version: '2'
services:
  app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate:fresh --seed && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=daw
      - MYSQL_USER=sail
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8070:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
